version: '3'

volumes:
  nfs-transmission-downloads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.168.40,rw
      device: ":/volume1/Transmission/downloads"

services:
  purevpn:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: jtmotox/purevpn-proxy:latest
    container_name: purevpn-proxy
    env_file: my.env
    hostname: purevpn-proxy
    privileged: true
    restart: always
    ports:
      - "1080:1080" # socks5 proxy
      - "9091:9091" # transmission
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./build/scripts:/scripts
      - nfs-transmission-downloads:/var/lib/transmission-daemon/downloads
      - ./transmission/resume:/var/lib/transmission-daemon/.config/transmission-daemon/resume
      - ./transmission/torrents:/var/lib/transmission-daemon/.config/transmission-daemon/torrents
